PRN211_Project/PRN211_Project/Models/Question.cs
using System;
using System.Collections.Generic;

namespace PRN211_Project.Models
{
    public partial class Question
    {
        public Question()
        {
            Choices = new HashSet<Choice>();
        }

        public int QuestionId { get; set; }
        public int? QuizId { get; set; }
        public string? Type { get; set; }
        public string? Content { get; set; }
        public int Point { get; set; }

        public virtual Quiz? Quiz { get; set; }
        public virtual ICollection<Choice> Choices { get; set; }
    }
}

PRN211_Project/PRN211_Project/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PRN211_Project.Models;
using System.Data.SqlTypes;
using System.IO;
using System.Net.WebSockets;

namespace PRNBL5.Controllers
{
    public class QuestionController : Controller
    {
        //private readonly PRN211_BL5DBContext db;

        //public QuestionController(PRN211_BL5DBContext db)
        //{
        //    this.db = db;
        //}
        public async Task<IActionResult> List()
        {
            PRN211_BL5DBContext db=new PRN211_BL5DBContext();
            var e = await db.Questions.Include(e => e.Quiz).Include(e => e.Choices).ToListAsync();

            return View(e);

            //var questions = await db.Questions.Include(e => e.Choices).ToListAsync();
            //return View(questions);

        }
        public async Task<IActionResult> DetailQuestion(int id)
        {
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();

            Question q = new Question();
            q = db.Questions.FirstOrDefault(q => q.QuestionId == id);
            List<Choice> choices = new List<Choice>();
            choices = db.Choices.Where(c => c.QuestionId == id).ToList();

            ViewBag.Choice = choices;


            return View(q);
        }
        [HttpPost]
        public async Task<IActionResult> EditProcess(Question q, List<Choice> choices, int correctAnswerId)

        {
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();

            // Find the question by its ID
            var question = await db.Questions.FindAsync(q.QuestionId);

            if (question != null)
            {
                // Update the question content
                question.Content = q.Content;
                bool correctAnswerFound = false;
                // Update choices
                foreach (var updatedChoice in choices)
                {
                    var choice = await db.Choices.FindAsync(updatedChoice.ChoiceId);
                    if (choice != null)
                    {
                        choice.Content = updatedChoice.Content;

                        choice.IsCorrect = choice.ChoiceId == correctAnswerId;


                    }
                }
                await db.SaveChangesAsync();
            }
            return RedirectToAction("List");
        }


        [HttpGet]

        public async Task<IActionResult> AddQuestion()
        {
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();

            var quizzes = await db.Quizzes.ToListAsync(); // Fetch quizzes from your database
            ViewBag.Quizzes = new SelectList(quizzes, "QuizId", "Title");
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> AddQuestion(Question question, string answer, string[] c)
        {
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();



            // Add the question without specifying the ID
            db.Questions.Add(question);
            db.SaveChanges();

            // Get the ID of the added question
            int addedQuestionId = question.QuestionId;

            // Now associate the choices with the question using the retrieved ID

            for (int i = 0; i < c.Length; i++)
            {



                var choice = new Choice
                {
                    QuestionId = addedQuestionId,
                    Content = c[i],
                    // IsCorrect = content[i] == answer

                    IsCorrect = (answer == "1" || answer == "2" || answer == "3" || answer == "4")
                    && answer == (i + 1).ToString()


                };
                db.Choices.Add(choice);

            }
            db.SaveChanges();
            return RedirectToAction("List");
        }



        [HttpPost]
        public async Task<IActionResult> DeleteQuestion(int id)
        {
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();

            if (id <= 0)
            {
                return NotFound();
            }

            var question = await db.Questions
                .Include(q => q.Choices)
                .FirstOrDefaultAsync(q => q.QuestionId == id);

            if (question == null)
            {
                return NotFound();
            }

            db.Choices.RemoveRange(question.Choices);
            db.Questions.Remove(question);

            await db.SaveChangesAsync();

            TempData["msg"] = $"Deleted question with ID: {id}";
            return RedirectToAction("List");
        }



    }
}

PRN211_Project/PRN211_Project/Views/Question/AddQuestion.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN211_Project.Models
@model PRN211_Project.Models.Question

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Create Question</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 70%;
            margin: 20px auto;
            background-color: #fff;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            border: 1px solid #ccc;
            margin-bottom: 20px;
        }

            .table tr {
                border-bottom: 1px solid #ccc;
            }

            .table td {
                padding: 10px;
                border-right: 1px solid #ccc;
            }

        label {
            font-weight: bold;
        }

        input[type="radio"] {
            margin-right: 5px;
        }

        label[for^="answer"] {
            margin-right: 10px;
        }

        input[type="text"],
        input[type="number"],
        select {
            width: 100%;
            padding: 5px;
            box-sizing: border-box;
        }

        .btn {
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Create</h1>
        <form asp-controller="Question" asp-action="AddQuestion" method="post">
            <table class="table">
                <tr>
                    <td>
                        <label asp-for="Content">Question Content(*)</label>
                        <input type="text" asp-for="Content" class="form-control" required />
                        <span asp-validation-for="Content" class="text-danger"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label asp-for="Type">Question Type</label>
                        <input type="text" asp-for="Type" class="form-control" value="Multiple choice" readonly required />
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label asp-for="Point">Question Point</label>
                        <input type="number" min="0.1" step="0.1" asp-for="Point" class="form-control" required />
                        <span asp-validation-for="Point" class="text-danger"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Quiz</label>
                        <div class="form-group">
                            <select id="QuizId" asp-for="QuizId" class="form-control">
                                <option value="">-- Select Quiz --</option>
                                @foreach (var item in (SelectList)ViewBag.Quizzes)
                                {
                                    <option value="@item.Value">@item.Text</option>
                                }
                            </select>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Answers:</label><br>
                        <label>
                            <input type="radio" name="answer" value="1" required /> a)
                            <input class="form-control" type="text" name="c" required />
                        </label><br>
                        <label>
                            <input type="radio" name="answer" value="2" required /> b)
                            <input class="form-control" type="text" name="c" required />
                        </label><br>
                        <label>
                            <input type="radio" name="answer" value="3" required /> c)
                            <input class="form-control" type="text" name="c" required />
                        </label><br>
                        <label>
                            <input type="radio" name="answer" value="4" required /> d)
                            <input class="form-control" type="text" name="c" required />
                        </label><br>
                    </td>
                </tr>
            </table>

            <input type="submit" value="Add" class="btn btn-primary" />
            <a asp-controller="Question" asp-action="List" class="btn btn-secondary">Back to list</a>
        </form>
    </div>
</body>
</html>

PRN211_Project/PRN211_Project/Views/Question/AddQuestionById.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@using PRN211_Project.Models
@model PRN211_Project.Models.Question


<div style="margin: 0px auto; width: 70%">
    <h1 style="text-align: center">Create</h1>
    <form asp-controller="Question" asp-action="AddQuestion" method="post">
        <table class="table">
            <tr>
                <td>
                    <label asp-for="Content">Question Content(*)</label>
                    <input type="text" asp-for="Content" class="form-control" required />
                    <span asp-validation-for="Content" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="Type">Question Type(*)</label>
                    <input type="text" asp-for="Type" class="form-control" required />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </td>

                </
            </tr>
            <tr>
                <td>
                    <label asp-for="Point">Question Point</label>
                    <input type="number" min="0.1" asp-for="Point" class="form-control" required />
                    <span asp-validation-for="Point" class="text-danger"></span>
                </td>
            </tr>
            </tr>
            <label>Quiz</label>
            <td>
                <div class="form-group">
                    <input id="QuizId" asp-for="QuizId" value="@ViewBag.quizid" readonly class="form-control">
                    </input>
                </div>
            </td>
            </tr>
            <tr>
                <td>
                    <label>Answers:</label><br>
                    <label>
                        <input type="radio" name="answer" value="1" required /> a)
                        <input class="form-control" type="text" name="c" required />
                    </label><br>
                    <label>
                        <input type="radio" name="answer" value="2" required /> b)
                        <input class="form-control" type="text" name="c" required />
                    </label><br>
                    <label>
                        <input type="radio" name="answer" value="3" required /> c)
                        <input class="form-control" type="text" name="c" required
                    </label><br>
                    <label>
                        <input type="radio" name="answer" value="4" required /> d)
                        <input class="form-control" type="text" name="c" required />
                    </label><br>
                </td>
            </tr>
        </table>

        <br />

        <input type="submit" value="Add" class="btn btn-primary" />
        <a asp-controller="Question" asp-action="Index" class="btn btn-secondary">Back to list</a>
    </form>
</div>

<style>
    /* Center the form and give it some spacing */
    div {
        margin: 20px auto;
        width: 70%;
    }

    /* Center the heading */
    h1 {
        text-align: center;
    }

    /* Style the table */
    .table {
        width: 100%;
        border-collapse: collapse;
        border: 1px solid #ccc;
    }

        /* Style table rows */
        .table tr {
            border-bottom: 1px solid #ccc;
        }

        /* Style table cells */
        .table td {
            padding: 10px;
            border-right: 1px solid #ccc;
        }

    /* Style the form labels */
    label {
        font-weight: bold;
    }

    /* Style the radio buttons */
    input[type="radio"] {
        margin-right: 5px;
    }

    /* Add margin to the answer labels */
    label[for^="answer"] {
        margin-right: 10px;
    }

    /* Style the input fields */
    input[type="text"],
    input[type="number"],
    select {
        width: 100%;
        padding: 5px;
        box-sizing: border-box;
    }

    /* Style the buttons */
    .btn {
        margin-top: 10px;
    }
</style>

PRN211_Project/PRN211_Project/Views/Question/DetailQuestion.cshtml
@using PRN211_Project.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Question

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Edit Question</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
        }

        .container {
            width: 80%;
            margin: 50px auto;
            background-color: #fff;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        label {
            font-weight: bold;
            margin-bottom: 5px;
            display: block;
        }

        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="radio"] {
            margin-right: 5px;
            vertical-align: middle;
        }

        p {
            font-weight: bold;
            margin-top: 15px;
        }

        button {
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

            button:hover {
                background-color: #0056b3;
            }
    </style>
</head>
<body>
    <div class="container">
        <form asp-controller="Question" asp-action="EditProcess" method="post">
            <label for="questionText">Question Text:</label>
            <input type="hidden" asp-for="QuestionId" value="@Model.QuestionId" />
            <input type="text" asp-for="Content" value="@Model.Content" required />

            <p>Answers:</p>
            @for (int i = 0; i < ViewBag.Choice.Count; i++)
            {
                Choice c = ViewBag.Choice[i];
                <input type="hidden" name="choices[@i].ChoiceId" value="@c.ChoiceId" />

                <input type="radio" name="correctAnswerId" value="@c.ChoiceId" @(c.IsCorrect ? "checked" : "") />
                <input type="text" name="choices[@i].Content" value="@c.Content" required />
            }

            <button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

PRN211_Project/PRN211_Project/Views/Question/List.cshtml
@using PRN211_Project.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model List<Question>



<div style="display:flex; align-content:start; margin-top: 20px;margin-left:20px">
    <form asp-controller="Home" asp-action="HomePage">
        <button>Back to the Home Page</button>
    </form>
</div>
<div style="width:50%;float:left"> <a asp-controller="Question" asp-action="AddQuestion"> Create a new Question</a></div>
<div class="container mt-5">

    @if (TempData["msg"] != null)
    {
        <p id="message" style="color:red">@TempData["msg"]</p>

        <script>
            // Function to hide the message
            function hideMessage() {
                var message = document.getElementById("message");
                if (message) {
                    message.style.display = "none";
                }
            }

            // Call the hideMessage function after the specified delay
            setTimeout(hideMessage, 3000); // 3000 milliseconds = 3 seconds
        </script>
    }
    <table width="100%" border="1">
        <tr>
            <th>Quiz</th>
            <th>QuestionContent</th>
            <th>QuestionType</th>
            <th>QuestionPoint</th>
            <th colspan="2">Action</th>
        </tr>
        @foreach (var e in Model)
        {
            <tr>
                <td>@e.Quiz.Title</td>
                <td>@e.Content</td>
                <td>@e.Type</td>
                <td>@e.Point</td>
                <td>
                    <a asp-controller="Question" asp-action="DetailQuestion" asp-route-id="@e.QuestionId">Edit</a>
                </td>


                <td>
                    <form asp-controller="Question" asp-action="DeleteQuestion" method="post">

                        <button type="submit" asp-route-id="@e.QuestionId" asp-action="DeleteQuestion" class="btn-link">Delete</button>

                    </form>
                </td>


            </tr>
        }




    </table>
</div>
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
    }

    .container {
        width: 80%;
        margin: 50px auto;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        padding: 10px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    a {
        text-decoration: none;
    }

    .btn-link {
        background: none;
        border: none;
        color: #007bff;
        cursor: pointer;
    }

        .btn-link:hover {
            text-decoration: underline;
        }

</style>