PRN211_Project/PRN211_Project/Models/DoQuiz.cs
using System;
using System.Collections.Generic;

namespace PRN211_Project.Models
{
    public partial class DoQuiz
    {
        public int DoQuizzesId { get; set; }
        public int? UserId { get; set; }
        public int? QuizId { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public int? Score { get; set; }

        public virtual Quiz? Quiz { get; set; }
        public virtual User? User { get; set; }
    }
}

PRN211_Project/PRN211_Project/Models/Quiz.cs
using System;
using System.Collections.Generic;

namespace PRN211_Project.Models
{
    public partial class Quiz
    {
        public Quiz()
        {
            DoQuizzes = new HashSet<DoQuiz>();
            Questions = new HashSet<Question>();
            Reviews = new HashSet<Review>();
        }

        public int QuizId { get; set; }
        public string Title { get; set; } = null!;
        public TimeSpan? Time { get; set; }
        public int? SubjectId { get; set; }

        public virtual Subject? Subject { get; set; }
        public virtual ICollection<DoQuiz> DoQuizzes { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}

PRN211_Project/PRN211_Project/Controllers/DoQuizzController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PRN211_Project.Models;
using System.Drawing;

namespace PRN211_Project.Controllers
{
    public class DoQuizzController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AllHistory()
        {
            if (HttpContext.Session.GetInt32("UserRole") == null)
            {
                return RedirectToAction("HomePage", "Home");
            }
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();
            var DoQuizzes = db.DoQuizzes.Include(x => x.Quiz).Include(x => x.User).OrderByDescending(d => d.DoQuizzesId).ToList();
            ViewBag.DoQuizzes = DoQuizzes;
            return View();
        }

        public IActionResult HistoryByQuizz(int quizid)
        {
            if (HttpContext.Session.GetInt32("UserRole") == null)
            {
                return RedirectToAction("HomePage", "Home");
            }
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();
            var DoQuizzes = db.DoQuizzes.Include(x => x.Quiz).Include(x => x.User).Where(x => x.QuizId == quizid).OrderByDescending(d => d.DoQuizzesId).ToList();
            ViewBag.DoQuizzes = DoQuizzes;
            return View();
        }

        public IActionResult HistoryByUser(int userid)
        {
            if (HttpContext.Session.GetInt32("UserRole") == null)
            {
                return RedirectToAction("HomePage", "Home");
            }
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();
            var DoQuizzes = db.DoQuizzes.Include(x => x.Quiz).Include(x => x.User).Where(x => x.UserId == userid).OrderByDescending(d => d.DoQuizzesId).ToList();
            ViewBag.DoQuizzes = DoQuizzes;
            return View();
        }

        static void Shuffle<T>(List<T> list)
        {
            Random random = new Random();

            for (int i = list.Count - 1; i > 0; i--)
            {
                int j = random.Next(i + 1);
                T temp = list[i];
                list[i] = list[j];
                list[j] = temp;
            }
        }

        public IActionResult DoQuiz(int quizid, int questionid, int answer)
        {

            PRN211_BL5DBContext db = new PRN211_BL5DBContext();
            int maxQuestion = db.Questions.Where(q => q.QuizId == quizid).Max(q => q.QuestionId);
            //    ViewBag.countdown = DateTime.Now + db.Quizzes.Find(quizid).Time;
            if (questionid > maxQuestion)
            {
                return RedirectToAction("Result", quizid);
            }
            if ((questionid % 5) == 1)
            {
                var a = DateTime.Now + db.Quizzes.Find(quizid).Time;
                HttpContext.Session.SetString("time", ((DateTime.Now + db.Quizzes.Find(quizid).Time).ToString()));
                HttpContext.Session.SetString("start", (DateTime.Now).ToString());

                HttpContext.Session.SetInt32("point", 0);
            }

            DateTime sessionTime = DateTime.Parse(HttpContext.Session.GetString("time"));
            ViewBag.time = DateTime.Now + db.Quizzes.Find(quizid).Time;
            //      ViewBag.countdown = sessionTime - DateTime.Now;
            var questions = db.Questions.Where(q => q.QuestionId == questionid).ToList();
            List<Choice> choices = db.Choices.Where(q => q.QuestionId == questionid).ToList();
            Shuffle(choices);

            ViewBag.questions = questions;
            ViewBag.choices = choices;
            ViewBag.quizid = quizid;
            ViewBag.questionid = questionid + 1;
            ViewBag.start = DateTime.Now;
            Choice choice = db.Choices.Find(answer);
            if (choice != null)
            {
                if (choice.IsCorrect == true)
                {
                    int currentIntValue = HttpContext.Session.GetInt32("point") ?? 0;
                    HttpContext.Session.SetInt32("point", currentIntValue + db.Questions.Find(questionid).Point);
                }
            }
            return View();
        }

        public IActionResult DoQuizz(int quizid, int questionid, int answer)
        {
            if (HttpContext.Session.GetInt32("UserRole") == null)
            {
                return RedirectToAction("HomePage", "Home");
            }
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();
            int maxQuestion = db.Questions.Where(q => q.QuizId == quizid).Max(q => q.QuestionId);
            //    ViewBag.countdown = DateTime.Now + db.Quizzes.Find(quizid).Time;
            if (questionid > maxQuestion)
            {
                return RedirectToAction("Result", new { quizid = quizid });
            }
            if (questionid == db.Questions.Where(q => q.QuizId == quizid).Min(q => q.QuestionId))
            {
                var a = DateTime.Now + db.Quizzes.Find(quizid).Time;
                HttpContext.Session.SetString("time", ((DateTime.Now + db.Quizzes.Find(quizid).Time).ToString()));
                HttpContext.Session.SetString("start", (DateTime.Now).ToString());

                HttpContext.Session.SetInt32("point", 0);
            }

            DateTime sessionTime = DateTime.Parse(HttpContext.Session.GetString("time"));
            ViewBag.time = sessionTime;
            //      ViewBag.countdown = sessionTime - DateTime.Now;
            var questions = db.Questions.Where(q => q.QuestionId == questionid).ToList();
            List<Choice> choices = db.Choices.Where(q => q.QuestionId == questionid).ToList();
            Shuffle(choices);

            ViewBag.questions = questions;
            ViewBag.choices = choices;
            ViewBag.quizid = quizid;
            ViewBag.questionid = questionid + 1;
            ViewBag.start = DateTime.Now;
            Choice choice = db.Choices.Find(answer);
            if (choice != null)
            {
                if (choice.IsCorrect == true)
                {
                    int currentIntValue = HttpContext.Session.GetInt32("point") ?? 0;
                    HttpContext.Session.SetInt32("point", currentIntValue + db.Questions.Find(questionid).Point);
                }
            }
            return View();
        }

        public IActionResult AllQuiz()
        {
            if (HttpContext.Session.GetInt32("UserRole") == null)
            {
                return RedirectToAction("HomePage", "Home");
            }
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();
            var quiz = db.Quizzes.Include(q => q.Subject).ToList();
            ViewBag.quiz = quiz;
            return View();
        }

        public IActionResult Quiz(int quizid)
        {
            if (HttpContext.Session.GetInt32("UserRole") == null)
            {
                return RedirectToAction("HomePage", "Home");
            }
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();
            HttpContext.Session.SetString("time", DateTime.Now.ToString());
            Quiz quiz = db.Quizzes.Find(quizid);
            ViewBag.subject = db.Subjects.Find(quiz.SubjectId).SubjectName;
            int questionid = db.Questions.Where(q => q.QuizId == quizid).Min(q => q.QuestionId);
            ViewBag.questionid = questionid;
            ViewBag.quizid = quizid;

            return View(quiz);
        }




        public IActionResult Result(int quizid)
        {
            PRN211_BL5DBContext db = new PRN211_BL5DBContext();
            DateTime start = DateTime.Parse(HttpContext.Session.GetString("start"));
            ViewBag.start = start;
            ViewBag.end = (DateTime.Now).ToString("dddd,d MMM yyyy,HH:mm tt");
            TimeSpan timeDifference = DateTime.Now - DateTime.Parse(HttpContext.Session.GetString("start"));
            ViewBag.time = timeDifference.ToString("hh':'mm':'ss");
            var id = HttpContext.Session.GetInt32("UserId");
            ViewBag.name = db.Users.Find(id).Username;
            ViewBag.point = HttpContext.Session.GetInt32("point");
            DoQuiz doQuiz = new DoQuiz();
            doQuiz.UserId = id;
            doQuiz.QuizId = quizid;
            doQuiz.StartTime = start;
            doQuiz.EndTime = DateTime.Now;
            doQuiz.Score = HttpContext.Session.GetInt32("point");
            Console.WriteLine("userid:" + doQuiz.UserId);
            Console.WriteLine(quizid);
            Console.WriteLine("quizid: " + doQuiz.QuizId);
            db.Add(doQuiz);
            db.SaveChanges();
            return View();
        }
    }
}

PRN211_Project/PRN211_Project/Views/DoQuizz/AllHistory.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN211_Project.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz History</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        .quiz-history {
            list-style: none;
            padding: 0;
        }

        .quiz-item {
            border-bottom: 1px solid #ddd;
            padding: 10px 0;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

            .quiz-item .text {
                font-size: 14px;
                color: #888;
            }

            .quiz-item .score {
                font-size: 18px;
                font-weight: bold;
                color: #4caf50;
            }
    </style>
</head>
<body>
    <div style="display:flex; align-content:start; margin-top: 20px;margin-left:20px">
        <form asp-controller="Home" asp-action="HomePage">
            <button>Back to the Home Page</button>
        </form>
    </div>
    <div class="container">
        <h1>Quiz History</h1>
        <ul class="quiz-history">
            <li class="quiz-item">
                <span class="text"><h3>User</h3></span>
                <span class="text"><h3>Quizz</h3></span>
                <span class="score"><h3>Score</h3></span>
            </li>
            @foreach (DoQuiz d in @ViewBag.DoQuizzes)
            {
                <li class="quiz-item">
                    <span class="text">@d.User.Username <a asp-controller="DoQuizz" asp-action="HistoryByUser" asp-route-userid="@d.UserId">see history</a></span>
                    <span class="text">@d.Quiz.Title <a asp-controller="DoQuizz" asp-action="HistoryByQuizz" asp-route-quizid="@d.QuizId">see history</a></span>
                    <span class="score">@(d.Score)/10</span>
                </li>
            }

        </ul>
    </div>
</body>
</html>

PRN211_Project/PRN211_Project/Views/DoQuizz/AllQuiz.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN211_Project.Models

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Exam Selection</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
        }

        .exam-row {
            display: flex;
            gap: 20px;
            margin-bottom: 20px;
        }

        .exam-box {
            flex: 1;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }

        .exam-title {
            font-weight: bold;
            margin-bottom: 5px;
        }

        .exam-details {
            margin-top: 5px;
            font-size: 14px;
            color: #666;
        }

        .start-button {
            display: block;
            text-align: center;
            margin-top: 10px;
            text-decoration: none;
            background-color: #3498db;
            color: white;
            padding: 5px 10px;
            border-radius: 3px;
        }
    </style>
</head>
<body>
    <h1>Online Exam Selection</h1>
    <div class="exam-row">
        @foreach (Quiz q in ViewBag.quiz)
        {
            <div class="exam-box">
                <p class="exam-title">@q.Title</p>
                <p class="exam-details">Time: @q.Time</p>
                <p class="exam-details">Subject: @q.Subject.SubjectName</p>
                <a class="start-button" asp-controller="DoQuizz" asp-action="Quiz" asp-route-quizid="@q.QuizId">Start Exam</a>
            </div>
        }

    </div>
    <!-- You can add more exam rows here -->
</body>
</html>

PRN211_Project/PRN211_Project/Views/DoQuizz/DoQuiz.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN211_Project.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exam Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }

        .exam-container {
            max-width: 800px;
            margin: 100px auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
        }

        .question h1 {
            font-size: 24px;
            margin-bottom: 10px;
        }

        .options label {
            display: block;
            margin-bottom: 10px;
        }

        button {
            display: block;
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

            button:hover {
                background-color: #0056b3;
            }

        #countdown {
            font-size: 48px;
            font-weight: bold;
            color: #333;
            margin-left: 150px
        }
    </style>
</head>
<body>

    <div class="exam-container">
        <div id="countdown"></div>
        <br />

        <form id="quizForm" asp-controller="DoQuizz" asp-action="Result" asp-route-userid="@ViewBag.userid">
            @foreach (Question q in @ViewBag.questions)
            {

                <div class="question">
                    @if ((q.QuestionId % 5) == 0)
                    {
                        <h1>Question 5:</h1>
                    }
                    @if ((q.QuestionId % 5) != 0)
                    {
                        <h1>Question @(q.QuestionId % 5):</h1>
                    }
                    <p>@q.Content</p>
                </div>
                <div class="options">
                    @foreach (Choice c in @ViewBag.choices)
                    {
                        @if (c.QuestionId == q.QuestionId)
                        {
                            <label>
                                <input id="point" type="radio" name="@c.QuestionId" value="@c.IsCorrect" onclick="change()"> @c.Content
                            </label>
                        }
                    }
                </div>
                <br />

            }
            <button id="submitBtn" type="submit">Submit Quiz</button>
        </form>
    </div>
    <script>

        const countdownEndTime = new Date("@ViewBag.time");

        function updateCountdown() {
            const currentTime = new Date().getTime();
            const timeRemaining = countdownEndTime - currentTime;

            if (timeRemaining <= 0) {
                window.location.href = '@Url.Action("Result", "DoQuizz")';

            } else {
                const seconds = Math.floor(timeRemaining / 1000);
                const minutes = Math.floor(seconds / 60);
                const remainingSeconds = seconds % 60;

                const formattedTime = `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
                document.getElementById("countdown").textContent = `Time remaining: ${formattedTime}`;
            }
        }

        // Update the countdown every second
        updateCountdown();
        setInterval(updateCountdown, 1000);


        function change() {
            window.location.href = '@Url.Action("Result", "DoQuizz")';
        }


        $(document).ready(function () {
            $('input[type="radio"]').on('click', function () {
                var selectedValue = $('input[name="answer"]:checked').val();

                // Make AJAX request
                $.ajax({
                    type: 'POST', // Or 'GET' depending on your server setup
                    url: '/your-server-endpoint', // Replace with your server endpoint
                    data: { value: selectedValue },
                    success: function (response) {
                        $('#result').html(response);
                    },
                    error: function (error) {
                        console.error(error);
                    }
                });
            });
        });
    </script>
</body>
</html>

PRN211_Project/PRN211_Project/Views/DoQuizz/DoQuizz.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN211_Project.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exam Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }

        .exam-container {
            max-width: 800px;
            margin: 100px auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
        }

        .question h1 {
            font-size: 24px;
            margin-bottom: 10px;
        }

        .options label {
            display: block;
            margin-bottom: 10px;
        }

        button {
            display: block;
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

            button:hover {
                background-color: #0056b3;
            }

        #countdown {
            font-size: 48px;
            font-weight: bold;
            color: #333;
            margin-left: 150px
        }
    </style>
</head>
<body>

    <div class="exam-container">
        <div id="countdown"></div>
        <br />
        <form id="quizForm" asp-controller="DoQuizz" asp-action="DoQuizz" asp-route-quizid="@ViewBag.quizid" asp-route-questionid="@ViewBag.questionid">
            @foreach (Question q in @ViewBag.questions)
            {
                <div class="question">
                    @if ((q.QuestionId % 5) == 0)
                    {
                        <h1>Question 5:</h1>
                    }
                    @if ((q.QuestionId % 5) != 0)
                    {
                        <h1>Question @(q.QuestionId % 5):</h1>
                    }
                    <p>@q.Content</p>
                </div>
                <div class="options">
                    @foreach (Choice c in @ViewBag.choices)
                    {
                        <label>
                            @*<input id="point" type="radio" name="answer" value="@c.ChoiceId" onclick="change()"> @c.Content*@
                            @Html.RadioButton("answer",@c.ChoiceId) <span>@c.Content</span>
                        </label>
                    }
                </div>
                <br />

            }
            <div style="display:flex">
                <button id="submitBtn" type="submit">Next Page</button>
            </div>
        </form>
    </div>
    <script>

        const countdownEndTime = new Date("@ViewBag.time");

        function updateCountdown() {
            const currentTime = new Date().getTime();
            const timeRemaining = countdownEndTime - currentTime;
            if (timeRemaining === 5){
                alert("You have 5 more seconds");
            }
            var url = '@Url.Action("Result", "DoQuizz")' + '?quizid=@ViewBag.quizid'
            if (timeRemaining <= 0) {

                window.location.href = url;

            } else {
                const seconds = Math.floor(timeRemaining / 1000);
                const minutes = Math.floor(seconds / 60);
                const remainingSeconds = seconds % 60;

                const formattedTime = `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
                document.getElementById("countdown").textContent = `Time remaining: ${formattedTime}`;
            }
        }

        // Update the countdown every second
        updateCountdown();
        setInterval(updateCountdown, 1000);


        function change() {
            window.location.href = '@Url.Action("Result", "DoQuizz")';
        }


    
    </script>
</body>
</html>

PRN211_Project/PRN211_Project/Views/DoQuizz/HistoryByQuizz.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN211_Project.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz History</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        .quiz-history {
            list-style: none;
            padding: 0;
        }

        .quiz-item {
            border-bottom: 1px solid #ddd;
            padding: 10px 0;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

            .quiz-item .text {
                font-size: 14px;
                color: #888;
            }

            .quiz-item .score {
                font-size: 18px;
                font-weight: bold;
                color: #4caf50;
            }
    </style>
</head>
<body>
    <div style="display:flex; align-content:start; margin-top: 20px;margin-left:20px">
        <form asp-controller="Home" asp-action="HomePage">
            <button>Back to the Home Page</button>
        </form>
    </div>
    <div class="container">
        <form asp-controller="DoQuizz" asp-action="AllHistory">
            <button>Back</button>
        </form>
        <h1>Quiz History</h1>

        <ul class="quiz-history">
            <li class="quiz-item">
                <span class="text"><h3>User</h3></span>
                <span class="text"><h3>Quizz</h3></span>
                <span class="score"><h3>Score</h3></span>
            </li>
            @foreach (DoQuiz d in @ViewBag.DoQuizzes)
            {
                <li class="quiz-item">
                    <span class="text">@d.User.Username</span>
                    <span class="text">@d.Quiz.Title</span>
                    <span class="score">@(d.Score)/10</span>
                </li>
            }

        </ul>
    </div>
</body>
</html>

PRN211_Project/PRN211_Project/Views/DoQuizz/HistoryByUser.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN211_Project.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz History</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        .quiz-history {
            list-style: none;
            padding: 0;
        }

        .quiz-item {
            border-bottom: 1px solid #ddd;
            padding: 10px 0;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

            .quiz-item .text {
                font-size: 14px;
                color: #888;
            }

            .quiz-item .score {
                font-size: 18px;
                font-weight: bold;
                color: #4caf50;
            }
    </style>
</head>
<body>
    <div style="display:flex; align-content:start; margin-top: 20px;margin-left:20px">
        <form asp-controller="Home" asp-action="HomePage">
            <button>Back to the Home Page</button>
        </form>
    </div>
    <div class="container">
        <form asp-controller="DoQuizz" asp-action="AllHistory">
            <button>Back</button>
        </form>
        <h1>Quiz History</h1>
   
        <ul class="quiz-history">
            <li class="quiz-item">
                <span class="text"><h3>User</h3></span>
                <span class="text"><h3>Quizz</h3></span>
                <span class="score"><h3>Score</h3></span>
            </li>
            @foreach (DoQuiz d in @ViewBag.DoQuizzes)
            {
                <li class="quiz-item">
                    <span class="text">@d.User.Username</span>
                    <span class="text">@d.Quiz.Title</span>
                    <span class="score">@(d.Score)/10</span>
                </li>
            }

        </ul>
    </div>
</body>
</html>

PRN211_Project/PRN211_Project/Views/DoQuizz/Quiz.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN211_Project.Models
@model Quiz
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Exam Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
        }

        .exam {
            border: 1px solid #ccc;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

            .exam h2 {
                margin-top: 0;
            }

            .exam p {
                margin: 10px 0;
            }
    </style>
</head>
<body>
    <div class="exam">
        <h2>@Model.Title</h2>
        <p><strong>Subject:</strong> @ViewBag.subject</p>
        <p><strong>Time:</strong> @Model.Time</p>
        <p><strong>Instructions:</strong> This online quiz will cover various topics in @ViewBag.subject. Make sure you have a stable internet connection and a quiet environment to take the exam.</p>
        <p><strong>Access Link:</strong> <a asp-controller="DoQuizz" asp-action="DoQuizz" asp-route-quizid="@ViewBag.quizid" asp-route-questionid="@ViewBag.questionid">Click here to access the exam</a></p>
    </div>
</body>
</html>

PRN211_Project/PRN211_Project/Views/DoQuizz/Result.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN211_Project.Models

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Results</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
        }

        .score {
            font-size: 27px;
        }
    </style>
</head>
<body>
    <h1>Test Results</h1>
    <p>Hello, <span>@ViewBag.name</span>!</p>
    @*<p>Start exam at: @ViewBag.start</p>*@
    <p>Submitted @ViewBag.end</p>
    <p>Your time: @ViewBag.time</p>
    <p class="score">Your score: @ViewBag.point <span class="score" id="userScore"></span></p>
        <form asp-controller="Home" asp-action="HomePage">
            <button>Back to the Home Page</button>
        </form>
    <script>
        // Replace these placeholders with actual user name and score
        var userName = "@ViewBag.name";
        var userScore = 2


        // Update content with actual user data
        document.getElementById("userName").textContent = userName;
    </script>
</body>
</html>