PRN211_Project/PRN211_Project/Controllers/QuizzesController.cs
using PRN211_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Org.BouncyCastle.Asn1.Ess;

namespace Demo.Controllers
{
    public class QuizzesController : Controller
    {

        private readonly PRN211_BL5DBContext db;
        public QuizzesController(PRN211_BL5DBContext db)
        { 
            this.db = db; 
        }

        public async Task<IActionResult> Index()
        {
            var quizzes = await db.Quizzes
            .Include(q => q.Subject)
            .ToListAsync();
            return View(quizzes);
        }

        public IActionResult Detail(int id)
        {
            var quiz = db.Quizzes
                .Include(q => q.Subject) // Include để load thông tin môn học liên quan
                .FirstOrDefault(q => q.QuizId == id);

            if (quiz == null)
            {
                return NotFound();
            }

            return View(quiz);
        }

        public IActionResult Create()
        {

            // Lấy danh sách môn học từ database
            var subjects = db.Subjects.ToList();

            // Chuyển danh sách môn học thành SelectList để truyền vào View
            ViewBag.Subjects = new SelectList(subjects, "SubjectId", "SubjectName");

            return View();
        }


        [HttpPost]
        public IActionResult Create(Quiz quiz)
        {
            if (ModelState.IsValid)
            {
               
                // Lấy subject từ database dựa vào SubjectId được chọn
                var selectedSubject = db.Subjects.Find(quiz.SubjectId);
                if (selectedSubject == null)
                {
                    ModelState.AddModelError("SubjectId", "Invalid subject selection.");
                    return View(quiz);
                }

                Quiz newQuiz = new Quiz();
                newQuiz.Title = quiz.Title;
                newQuiz.Time = quiz.Time;
                newQuiz.Subject = selectedSubject; // Gán subject đã chọn vào đề thi
                db.Quizzes.Add(newQuiz);
                db.SaveChanges();
                return RedirectToAction("AddQuestion", "Question");
            }

            // Nếu ModelState không hợp lệ, trả về View với thông tin quiz và danh sách môn học
            ViewBag.Subjects = new SelectList(db.Subjects.ToList(), "SubjectId", "SubjectName");
            return View(quiz);
        }

        public IActionResult Edit(int id)
        {
            var quiz = db.Quizzes.Find(id);
            if (quiz == null)
            {
                return NotFound();
            }

            return View(quiz);
        }

        [HttpPost]
        public IActionResult Edit(Quiz quiz)
        {
            if (ModelState.IsValid)
            {
                db.Quizzes.Update(quiz);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(quiz);
        }

        public IActionResult Delete(int id)
        {
            var quiz = db.Quizzes.Find(id);
            if (quiz == null)
            {
                return NotFound();
            }

            return View(quiz);
        }

        public IActionResult DeleteConfirmed(int id)
        {
            Quiz quiz = db.Quizzes.Find(id);
            if (quiz == null)
            {
                return NotFound();
            }
            var listquestion = db.Questions.Where(q => q.QuizId == id).ToList();
            foreach(Question question in listquestion)
            {
                var listchoice = db.Choices.Where(c => c.QuestionId == question.QuestionId).ToList();
                foreach(Choice choice in listchoice)
                {
                    db.Choices.Remove(choice);
                    db.SaveChanges();
                }
                db.Questions.Remove(question);
                db.SaveChanges();
            }
            db.Quizzes.Remove(quiz);
            db.SaveChanges();
            
            return RedirectToAction("Index");
        }

        public IActionResult CreateSubject()
        {
            var subjects = db.Subjects.ToList();
            ViewBag.ExistingSubjects = subjects;
            return View();
        }

        [HttpPost]
        public IActionResult CreateSubject(string newSubjectName)
        {
            if (!string.IsNullOrWhiteSpace(newSubjectName))
            {
                var newSubject = new Subject { SubjectName = newSubjectName };
                db.Subjects.Add(newSubject);
                db.SaveChanges();

                TempData["SuccessMessage"] = "Subject created successfully.";
            }

            return RedirectToAction("CreateSubject");
        }

        public IActionResult EditSubject(int id)
        {
            var subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        [HttpPost]
        public IActionResult EditSubject(Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Subjects.Update(subject);
                db.SaveChanges();
                return RedirectToAction("CreateSubject");
            }

            return View(subject);
        }
    }
}

PRN211_Project/PRN211_Project/Views/Quizzes/Create.cshtml
@using PRN211_Project.Models
@model PRN211_Project.Models.Quiz
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<head>
    <title>Create Quiz</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body {
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
        }

        .container {
            margin-top: 50px;
        }

        h1 {
            color: #333;
            margin-bottom: 20px;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border: 1px solid #dcdcdc;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"],
        select {
            width: 100%;
            padding: 10px;
            border: 1px solid #dcdcdc;
            border-radius: 5px;
            font-size: 14px;
        }

        .text-danger {
            color: #dc3545;
        }

        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }

            .btn-primary:hover {
                background-color: #0056b3;
                border-color: #0056b3;
            }

            .btn-primary:focus {
                box-shadow: none;
            }

            .btn-primary:active {
                background-color: #004080;
                border-color: #004080;
            }

        .btn-link {
            color: #007bff;
            text-decoration: none;
        }

            .btn-link:hover {
                text-decoration: underline;
            }

        .back-link {
            margin-top: 20px;
        }
    </style>
</head>

<form method="post" asp-controller="Quizzes" asp-action="Create">
    <div class="form-group">
        <label for="Title">Title</label>
        <input type="text" class="form-control" asp-for="Title" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Time" class="control-label">Time</label>
        <input asp-for="Time" class="form-control" /> 
        <label>(Please enter by format: hh:mm:ss)</label>
        <span asp-validation-for="Time" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="SubjectId">Subject</label>
        <select class="form-control" asp-for="SubjectId" asp-items="@ViewBag.Subjects">
            <option value="">Select a subject</option>
        </select>
        <span asp-validation-for="SubjectId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>




<div>
    <a asp-action="Index">Back to List</a>
</div>

PRN211_Project/PRN211_Project/Views/Quizzes/CreateSubject.cshtml
@model PRN211_Project.Models.Subject
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Create Subject</h1>

<head>
    <title>Create Subject</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body {
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
        }

        .container {
            margin-top: 50px;
        }

        h1 {
            color: #333;
            margin-bottom: 20px;
            text-align: center;
        }

        .table {
            margin-bottom: 30px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #dcdcdc;
            border-radius: 5px;
            font-size: 14px;
        }

        .text-danger {
            color: #dc3545;
        }

        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }

            .btn-primary:hover {
                background-color: #0056b3;
                border-color: #0056b3;
            }

            .btn-primary:focus {
                box-shadow: none;
            }

            .btn-primary:active {
                background-color: #004080;
                border-color: #004080;
            }

        .btn-link {
            color: #007bff;
            text-decoration: none;
        }

            .btn-link:hover {
                text-decoration: underline;
            }

        .back-link {
            margin-top: 20px;
        }

        hr {
            margin-top: 30px;
            margin-bottom: 30px;
            border: 0;
            border-top: 1px solid #dcdcdc;
        }

        /* Additional styling */
        .center-content {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .form-container {
            width: 400px;
            padding: 20px;
            background-color: #fff;
            border: 1px solid #dcdcdc;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .form-title {
            text-align: center;
            margin-bottom: 20px;
        }

        .form-button {
            text-align: center;
            margin-top: 20px;
        }

        /* Center the existing subjects table */
        .existing-subjects {
            text-align: center;
            margin-bottom: 20px;
        }

        /* Styling for table cells */
        .table-cell {
            vertical-align: middle;
        }
    </style>
</head>


<body>
    <div class="center-content">
        <div class="form-container">
            <div class="form-title">
                <h1>Create Subject</h1>
            </div>
            <div class="existing-subjects">
                <h2>Existing Subjects</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Subject Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var subject in ViewBag.ExistingSubjects)
                        {
                            <tr>
                                <td class="table-cell">@subject.SubjectName</td>
                                <td class="table-cell">
                                    <a href="@Url.Action("EditSubject", "Quizzes", new { id = subject.SubjectId })">Edit</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <hr />

            <form method="post" asp-controller="Quizzes" asp-action="CreateSubject">
                <div class="form-group">
                    <label for="newSubjectName">New Subject Name</label>
                    <input type="text" class="form-control" name="newSubjectName" />
                    <span class="text-danger"></span>
                </div>
                <div class="form-button">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>

            <div class="back-link">
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</body>

<hr />
<div>
    <a asp-action="Index">Back to List</a>
</div>

PRN211_Project/PRN211_Project/Views/Quizzes/Delete.cshtml
@using PRN211_Project.Models
@model PRN211_Project.Models.Quiz
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h2>Delete Quiz</h2>

<h3>Are you sure you want to delete this quiz?</h3>
<div>
    <h4>Quiz</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class="col-sm-10">
            @(Model.Time.HasValue ? Model.Time.ToString() : "")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SubjectId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SubjectId)
        </dd>
    </dl>
    <form asp-action="DeleteConfirmed" asp-controller="Quizzes" asp-route-id="@Model.QuizId">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PRN211_Project/PRN211_Project/Views/Quizzes/Detail.cshtml
@model PRN211_Project.Models.Quiz
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html>
<head>
    <title>Detail Quiz</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body {
            background-color: #f8f9fa;
        }

        .container {
            margin-top: 50px;
        }

        .quiz-details {
            border: 1px solid #dee2e6;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

            .quiz-details h2 {
                margin-bottom: 20px;
            }

            .quiz-details dl {
                display: grid;
                grid-template-columns: auto 1fr;
                row-gap: 10px;
                margin-bottom: 20px;
            }

            .quiz-details dt {
                font-weight: bold;
            }

            .quiz-details a {
                display: inline-block;
                margin-top: 10px;
            }
    </style>
</head>
<body>
    <div class="container">
        <div class="quiz-details">
            <h2>Detail Quiz</h2>
            <hr />
            <dl>
                <dt>Title:</dt>
                <dd>@Html.DisplayFor(model => model.Title)</dd>
                <dt>Time:</dt>
                <dd>@(Model.Time.HasValue ? Model.Time.ToString() : "")</dd>
                <dt>Subject:</dt>
                <dd>@Html.DisplayFor(model => model.Subject.SubjectName)</dd>
            </dl>
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>
    </div>
</body>
</html>

PRN211_Project/PRN211_Project/Views/Quizzes/Edit.cshtml
@using PRN211_Project.Models
@model Quiz
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html>
<head>
    <title>Edit Quiz</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <div class="container">
        <h2>Edit Quiz</h2>

        <form asp-action="Edit" class="mt-4">
            <input type="hidden" asp-for="QuizId" />

            <div class="form-group">
                <label asp-for="Title" class="control-label">Title</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Time" class="control-label">Time</label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SubjectId" class="control-label">SubjectId</label>
                <input asp-for="SubjectId" class="form-control" />
                <span asp-validation-for="SubjectId" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
        </form>

        <div class="mt-3">
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>

        @if (ViewData["ErrorMessage"] != null)
        {
            <div class="mt-3 alert alert-danger">
                @ViewData["ErrorMessage"]
            </div>
        }
        @if (ViewData["SuccessMessage"] != null)
        {
            <div class="mt-3 alert alert-success">
                @ViewData["SuccessMessage"]
            </div>
        }
    </div>

</body>
</html>

PRN211_Project/PRN211_Project/Views/Quizzes/EditSubject.cshtml
@model PRN211_Project.Models.Subject
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Edit Subject</h1>

<form method="post" asp-controller="Quizzes" asp-action="EditSubject">
    <input type="hidden" asp-for="SubjectId" />

    <div class="form-group">
        <label for="SubjectName">Subject Name</label>
        <input type="text" class="form-control" asp-for="SubjectName" />
        <span asp-validation-for="SubjectName" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PRN211_Project/PRN211_Project/Views/Quizzes/Index.cshtml
@model List<PRN211_Project.Models.Quiz>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html>
<head>
    <title>Quizzes List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body {
            background-color: #f8f9fa;
        }

        .container {
            margin-top: 50px;
        }

        .table {
            border: 1px solid #dee2e6;
            border-collapse: collapse;
            width: 100%;
        }

            .table th, .table td {
                border: 1px solid #dee2e6;
                padding: 8px;
                text-align: center;
            }

            .table th {
                background-color: #f2f2f2;
            }

        .btn-group {
            margin-right: 10px;
        }

        .btn {
            border-radius: 5px;
            margin-right: 5px;
        }

        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }

        .btn-secondary {
            background-color: #6c757d;
            border-color: #6c757d;
        }


        h2 {
            color: #333;
        }

        .mb-3 {
            margin-bottom: 20px;
        }

        .btn-sm {
            font-size: 12px;
        }
    </style>
</head>
<body>
    
    <div class="container">
        <h2 class="mb-4">Quizzes</h2>
        <div class="mb-3">
            <a asp-controller="Quizzes" asp-action="Create" class="btn btn-primary">Create a new Quiz</a> <br />
            <a asp-controller="Quizzes" asp-action="CreateSubject" class="btn btn-secondary">Create Subject</a>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Time</th>
                    <th>Subject ID</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var quiz in Model)
                {
                    <tr>
                        <td>@quiz.Title</td>
                        <td>@(quiz.Time.HasValue ? quiz.Time.ToString() : "")</td>
                        <td>@quiz.Subject.SubjectName</td>
                        <td>
                            <div class="btn-group">
                                <a asp-controller="Quizzes" asp-action="Detail" asp-route-id="@quiz.QuizId" class="btn btn-info btn-sm">Detail</a>
                                <a asp-controller="Quizzes" asp-action="Edit" asp-route-id="@quiz.QuizId" class="btn btn-warning btn-sm">Edit</a>
                                <a asp-controller="Quizzes" asp-action="Delete" asp-route-id="@quiz.QuizId" class="btn btn-danger btn-sm">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div style="display:flex; align-content:start; margin-top: 20px;margin-left:20px">
            <form asp-controller="Home" asp-action="HomePage">
                <button>Back to the Home Page</button>
            </form>
        </div>
    </div>
</body>
</html>